name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    env:
      ReleaseFilePath: app/build/outputs/apk/release

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build the app
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign
        with:
          releaseDirectory: ${{ env.ReleaseFilePath }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: droiddemo
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Get version
        id: get-version
        run: echo "tagVersion=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Pre Release Process
        run: |
          mv ${{steps.sign.outputs.signedReleaseFile}} ${{ env.ReleaseFilePath }}/DroidDemo-signed-${{ steps.get-version.outputs.tagVersion }}.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ReleaseFilePath }}/DroidDemo-signed-${{ steps.get-version.outputs.tagVersion }}.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false